name: Deploy Mye3-Elearning

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🏗️ Build Frontend (Vite)
        run: |
          cd frontend
          npm install
          npm run build
        env:
          # Ikkada kotha domain spelling 'i' tho update chesa
          VITE_API_URL: https://mye3etuitions.com/api

      - name: 🚀 Deploy Frontend to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: frontend/dist/
          server-dir: mye3etuitions.com/
          parallel: 1
          timeout: 600000

      - name: 🚀 Deploy Backend to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: backend/
          server-dir: mye3etuitions.com/backend/
          parallel: 1
          timeout: 600000
          exclude: |
            **/node_modules/**
            **/debug.log
            .git*